config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "teams#index"
  resources :teams do
    resources :players
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_team
  before_action :set_player, only: [:edit, :update, :show, :destroy]

  def index 
    @players = @team.players
  end

  def show
  end
  
  def edit
  end

  def new
    @player = @team.players.new
  end

  def update
    if @player.update(player_params)
      redirect_to [@team, @player]
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to team_players_path
  end

  def create
    @player = @team.players.new(player_params)
    if (@player.save)
      redirect_to [@team, @player]
    else
      render :new
    end
  end


  
  private
  def set_team
    @team = Team.find(params[:team_id])
  end

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :age, :position, :height, :weight, :number)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:edit, :update, :destroy, :show]

  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if (@team.save)
      redirect_to teams_path
    else
      render :new
    end
  end

  def edit
  end

  def update 
    if(@team.update(team_params))
      redirect_to @team
    else
      render :edit
    end
  end

  def destroy
    @team.destroy
    redirect_to teams_path
  end

  private
  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportTeams</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

  <div class="ui container">
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<h1><%=@player.id ? 'Edit Player' : 'Create Player'%> </h1>
<hr/>

<%= form_with(model:[@team, @player], local: true, class: 'ui form') do |f|%>
  <%=f.label :name, class:"field"%>
  <%=f.text_field :name, required: true, autofocus: true%>
  <br/>
  <%=f.label :age, class:"field"%>
  <%=f.text_field :age, required: true, autofocus: true%>
  <br/>
  <%=f.label :position, class:"field"%>
  <%=f.text_field :position, required: true, autofocus: true%>
  <br/>
  <%=f.label :number, class:"field"%>
  <%=f.text_field :number, required: true, autofocus: true%>
  <br/>
  <%=f.label :height, class:"field"%>
  <%=f.text_field :height, required: true, autofocus: true%>
    <br/>
  <%=f.label :weight, class:"field"%>
  <%=f.text_field :weight, required: true, autofocus: true%>
  <%= f.submit nil, class: "ui button" %>
<%end%>

app/views/players/edit.html.erb
<h1>Players#edit</h1>
<p>Find me in app/views/players/edit.html.erb</p>

app/views/players/index.html.erb
<h1>Roster</h1>
<%= link_to "Add new player",new_team_player_path(@team),class:'ui primary button'%>
<ul>
  <% @players.each do |player|%>
    <li class="ui list"><%= link_to player.name, [@team, player]%></li>
  <%end%>
</ul>
<%= link_to 'Back', teams_path%> 

app/views/players/new.html.erb
<%=render 'form', team: @team, player: @animal%>
<%= link_to "Back", team_players_path(@team) %>

app/views/players/show.html.erb
<h1><%=@team.name%>
<div class='ui list'>
<h4>Name: <%=@player.name%> </h4>
<h4>Age: <%=@player.age%> </h4>
<h4>Position: <%=@player.position%> </h4>
<h4>Number: <%=@player.number%> </h4>
<h4>Height: <%=@player.height%> </h4>
<h4>Weight: <%=@player.weight%> </h4>

<%= link_to "Back", team_players_path%>
</div>